// export const goals = [
// 	{
// 		className: 'main__aboutus__row__section',
// 		iconClass: 'fa-solid fa-mobile-screen',
// 		titleClass: 'main__aboutus__row__section__title',
// 		titleText: 'mobile gaming',
// 		textClass: 'main__aboutus__row__section__text',
// 		textContent: 'Tworzymy gry na urządzenia mobilne!',
// 	},
// 	{
// 		className: 'main__aboutus__row__section',
// 		iconClass: 'fa-solid fa-desktop',
// 		titleClass: 'main__aboutus__row__section__title',
// 		titleText: 'desktop gaming',
// 		textClass: 'main__aboutus__row__section__text',
// 		textContent: 'Tworzymy gry na PC!',
// 	},
// 	{
// 		className: 'main__aboutus__row__section',
// 		iconClass: 'fa-solid fa-file-code',
// 		titleClass: 'main__aboutus__row__section__title',
// 		titleText: 'najwyższe standardy',
// 		textClass: 'main__aboutus__row__section__text',
// 		textContent: 'Zachowujemy najwyższe standardy podczas pisania kodu.',
// 	},
// 	{
// 		className: 'main__aboutus__row__section',
// 		iconClass: 'fa-solid fa-paw',
// 		titleClass: 'main__aboutus__row__section__title',
// 		titleText: 'kochamy zwierzęta!',
// 		textClass: 'main__aboutus__row__section__text',
// 		textContent: 'Wszystkie nasze gry są bezpieczne dla środowiska 🙂',
// 	},
// 	{
// 		className: 'main__aboutus__row__section',
// 		iconClass: 'fa-solid fa-burger',
// 		titleClass: 'main__aboutus__row__section__title',
// 		titleText: 'lubimy dobre jedzenie',
// 		textClass: 'main__aboutus__row__section__text',
// 		textContent: 'Lubimy dobrze zjeść przed przystąpieniem do naszych zadań.',
// 	},
// 	{
// 		className: 'main__aboutus__row__section',
// 		iconClass: 'fa-solid fa-champagne-glasses',
// 		titleClass: 'main__aboutus__row__section__title',
// 		titleText: 'świetne relacje',
// 		textClass: 'main__aboutus__row__section__text',
// 		textContent: 'Zachowujemy świetne relacje z naszymi klientami!',
// 	},
// ];
